name: Artifact Uploading

on:
  push:
    branches: [ singleton ]
    paths:
    - '**.cs'
    - '**.csproj'
    - '.github/workflows/artifact_upload.yml'
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install DotNet v6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
          
      - name: Build
        run: |
          cd Core/

          dotnet build NiTiS/ -c ReleaseWithoutPack
          
      - name: Build Subs
        run: |
          cd Core/
          
          dotnet build NiTiS.Collections/ -c ReleaseWithoutPack -o ../.build/NiTiS.Collections/ --nologo --no-dependencies
          dotnet build NiTiS.Additions/ -c ReleaseWithoutPack -o ../.build/NiTiS.Additions/ --nologo --no-dependencies
          
          dotnet build NiTiS.Math/ -c ReleaseWithoutPack -o ../.build/NiTiS.Math/ --nologo --no-dependencies
          dotnet build NiTiS.Reflection/ -c ReleaseWithoutPack -o ../.build/NiTiS.Reflection/ --nologo --no-dependencies
          dotnet build NiTiS.IO/ -c ReleaseWithoutPack -o ../.build/NiTiS.IO/ --nologo --no-dependencies
          dotnet build NiTiS.Interaction/ -c ReleaseWithoutPack -o ../.build/NiTiS.Interaction/ --nologo --no-dependencies
          
          dotnet build NiTiS/ -c ReleaseWithoutPack -o ../.build/NiTiS.Core/ --nologo --no-dependencies
          
      - name: Artifact Pack 
        uses: actions/upload-artifact@v2
        with:
          path: .build/
          
