name: Artifact Publish

on:
  push:
    branches: [ singleton ]
    paths:
    - '**.cs'
    - '**.csproj'
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd Core
          cd NiTiS
          dotnet build -c Release
          dotnet pack -c Release -o ../../.build/NiTiS.Core
      - name: Artifact Pack 
        uses: actions/upload-artifact@v2
        with:
          path: .build/
          
