# This is a basic workflow to help you get started with Actions

name: Nuget Publish
# Controls when the workflow will run
on:
  push:
    branches: [ singleton ]
    paths:
    - '**.cs'
    - '**.csproj'
    - '.github/workflows/nuget_publish.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install DotNet v6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x' 
      
      - name: Build
        run: |
          cd Core/
          cd NiTiS
          dotnet build -c Release -o ../../.build/ --nologo
          dotnet pack -c Release -o ../../.build/ --nologo
      - name: Pack
        run: |
          cd Core/
          ls
          dotnet pack NiTiS.IO/ -c Release -o ../.build/ --nologo
          dotnet pack NiTiS.Collections/ -c Release -o ../.build/ --nologo
          dotnet pack NiTiS.Interaction/ -c Release -o ../.build/ --nologo
          dotnet pack NiTiS.Math/ -c Release -o ../.build/ --nologo
          dotnet pack NiTiS.Reflection/ -c Release -o ../.build/ --nologo
          dotnet pack NiTiS.Additions/ -c Release -o ../.build/ --nologo
      
      - name: PushNUGET
        run: |
          cd .build/
          ls
          dotnet nuget push NiTiSCore*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
          dotnet nuget push NiTiSCore*.snupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
          
          dotnet nuget push NiTiS.IO*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
          dotnet nuget push NiTiS.IO*.snupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
          
          dotnet nuget push NiTiS.Collections*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
          dotnet nuget push NiTiS.Collections*.snupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
          
          dotnet nuget push NiTiS.Interaction*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
          dotnet nuget push NiTiS.Interaction*.snupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
          
          dotnet nuget push NiTiS.Math*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
          dotnet nuget push NiTiS.Math*.snupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
          
          dotnet nuget push NiTiS.Reflection*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
          dotnet nuget push NiTiS.Reflection*.snupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
          
          dotnet nuget push NiTiS.Additions*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
          dotnet nuget push NiTiS.Additions*.snupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
          
      - name: PushGIT
        run: |
          cd .build/
          dotnet nuget push NiTiSCore*.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${GITHUB_TOKEN} --skip-duplicate
          dotnet nuget push NiTiS.IO*.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${GITHUB_TOKEN} --skip-duplicate
          dotnet nuget push NiTiS.Collections*.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${GITHUB_TOKEN} --skip-duplicate
          dotnet nuget push NiTiS.Interaction*.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${GITHUB_TOKEN} --skip-duplicate
          dotnet nuget push NiTiS.Math*.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${GITHUB_TOKEN} --skip-duplicate
          dotnet nuget push NiTiS.Reflection*.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${GITHUB_TOKEN} --skip-duplicate
          dotnet nuget push NiTiS.Additions*.nupkg --source https://nuget.pkg.github.com/acraven/index.json --api-key ${GITHUB_TOKEN} --skip-duplicate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
          
