name: Tag Publish Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install DotNet v6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.x' 

    - name: Build
      run: |
        dotnet build NiTiS.Collections/ -c ReleaseWithoutPack -o ../.build --nologo
        dotnet build NiTiS.Additions/ -c ReleaseWithoutPack -o ../.build --nologo
          
        dotnet build NiTiS.Math/ -c ReleaseWithoutPack -o ../.build --nologo
        dotnet build NiTiS.Reflection/ -c ReleaseWithoutPack -o ../.build --nologo
        dotnet build NiTiS.IO/ -c ReleaseWithoutPack -o ../.build --nologo
        dotnet build NiTiS.Interaction/ -c ReleaseWithoutPack -o ../.build --nologo
          
        dotnet build NiTiS/ -c ReleaseWithoutPack -o ../.build --nologo
          
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: .build/
        tag: ${{ github.ref }}
